// Dane mockowe do developmentu UI bez połączenia z Supabase
import type {
  DbProject,
  DbTask,
  DbCycle,
  DbUser,
  DbIdea,
  DbDocument,
  DbGoal,
  TaskWithRelations,
} from './supabase/types'

export const MOCK_USERS: DbUser[] = [
  { id: 'u1', email: 'ania@hotable.pl', full_name: 'Ania Kowalska', avatar_url: null, created_at: '2025-01-01T00:00:00Z' },
  { id: 'u2', email: 'marek@hotable.pl', full_name: 'Marek Nowak', avatar_url: null, created_at: '2025-01-01T00:00:00Z' },
  { id: 'u3', email: 'kasia@hotable.pl', full_name: 'Kasia Wiśniewska', avatar_url: null, created_at: '2025-01-01T00:00:00Z' },
]

export const MOCK_PROJECTS: DbProject[] = [
  {
    id: 'p1',
    name: 'Hotable MVP',
    scope_tag: 'scope_1.0',
    description: 'Główna platforma rezerwacji',
    color: '#4BAF87',
    is_archived: false,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Grant PARP FEPW',
    scope_tag: 'grant_parp',
    description: 'Milestony grantowe PARP',
    color: '#F5A83A',
    is_archived: false,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Marketing Q1',
    scope_tag: 'marketing',
    description: 'Kampanie i content',
    color: '#E8622A',
    is_archived: false,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

export const MOCK_CYCLE: DbCycle = {
  id: 'c4',
  name: 'Sprint 4 — Auth & Board',
  start_date: '2026-04-07',
  end_date: '2026-04-18',
  goal: 'Działający auth z magic link i w pełni funkcjonalny Sprint Board z drag-drop',
  is_active: true,
  velocity_planned: 9,
  velocity_actual: null,
  notes: null,
  sprint_links: null,
  unavailability: null,
  created_at: '2026-04-01T00:00:00Z',
}

export const MOCK_CYCLES: DbCycle[] = [
  {
    id: 'c1',
    name: 'Sprint 1 — Fundament',
    start_date: '2026-01-05',
    end_date: '2026-01-16',
    goal: 'Setup repo, Supabase, CI/CD, schema bazy',
    is_active: false,
    velocity_planned: 6,
    velocity_actual: 5,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c2',
    name: 'Sprint 2 — Design System',
    start_date: '2026-02-02',
    end_date: '2026-02-13',
    goal: 'Tailwind config, shadcn/ui, komponenty bazowe, sidebar',
    is_active: false,
    velocity_planned: 8,
    velocity_actual: 7,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-01-30T00:00:00Z',
  },
  {
    id: 'c3',
    name: 'Sprint 3 — Kanban & Backlog',
    start_date: '2026-03-02',
    end_date: '2026-03-13',
    goal: 'Sprint Board z drag-drop, widok Backlog, Quick Add',
    is_active: false,
    velocity_planned: 10,
    velocity_actual: 8,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-02-27T00:00:00Z',
  },
  {
    id: 'c4',
    name: 'Sprint 4 — Auth & Board',
    start_date: '2026-04-07',
    end_date: '2026-04-18',
    goal: 'Działający auth z magic link i w pełni funkcjonalny Sprint Board z drag-drop',
    is_active: true,
    velocity_planned: 9,
    velocity_actual: null,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'c5',
    name: 'Sprint 5 — Ideas & Decisions',
    start_date: '2026-05-04',
    end_date: '2026-05-15',
    goal: 'Ideas Inbox z ICE scoring, Decision Log, ADR/RFC',
    is_active: false,
    velocity_planned: null,
    velocity_actual: null,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-04-25T00:00:00Z',
  },
  {
    id: 'c6',
    name: 'Sprint 6 — OKR & Weekly',
    start_date: '2026-06-01',
    end_date: '2026-06-12',
    goal: 'Cele OKR, milestony PARP, weekly summary auto-gen',
    is_active: false,
    velocity_planned: null,
    velocity_actual: null,
    notes: null,
    sprint_links: null,
    unavailability: null,
    created_at: '2026-05-28T00:00:00Z',
  },
]

export const MOCK_TASKS: DbTask[] = [
  // TODO
  {
    id: 't1',
    title: 'Napisać RLS policies dla tabeli tasks',
    description: 'Każdy user widzi tylko taski ze swoich projektów',
    status: 'todo',
    priority: 'high',
    type: 'ops',
    project_id: 'p1',
    assignee_id: 'u1',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: '2026-04-15',
    position: 0,
    ai_suggested: false,
    deleted_at: null,
    size: 'M',
    story_points: 3,
    created_at: '2026-04-07T09:00:00Z',
    updated_at: '2026-04-07T09:00:00Z',
  },
  {
    id: 't2',
    title: 'Dokumentacja milestonu M2 — raport',
    description: null,
    status: 'todo',
    priority: 'urgent',
    type: 'ops',
    project_id: 'p2',
    assignee_id: 'u2',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: '2026-04-14',
    position: 1,
    ai_suggested: false,
    deleted_at: null,
    size: 'L',
    story_points: 5,
    created_at: '2026-04-07T09:01:00Z',
    updated_at: '2026-04-07T09:01:00Z',
  },
  {
    id: 't3',
    title: 'Przygotować wireframes widoku Backlog',
    description: null,
    status: 'todo',
    priority: 'medium',
    type: 'design',
    project_id: 'p1',
    assignee_id: 'u3',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: null,
    position: 2,
    ai_suggested: false,
    deleted_at: null,
    size: 'M',
    story_points: 3,
    created_at: '2026-04-08T10:00:00Z',
    updated_at: '2026-04-08T10:00:00Z',
  },
  {
    id: 't4',
    title: 'SEO meta tagi na stronę główną',
    description: null,
    status: 'todo',
    priority: 'low',
    type: 'marketing',
    project_id: 'p3',
    assignee_id: null,
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: null,
    position: 3,
    ai_suggested: false,
    deleted_at: null,
    size: 'S',
    story_points: 2,
    created_at: '2026-04-08T11:00:00Z',
    updated_at: '2026-04-08T11:00:00Z',
  },
  // IN PROGRESS
  {
    id: 't5',
    title: 'Implementacja magic link auth',
    description: 'Supabase Auth + @supabase/ssr, middleware ochrony tras',
    status: 'in_progress',
    priority: 'urgent',
    type: 'development',
    project_id: 'p1',
    assignee_id: 'u1',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: '2026-04-11',
    position: 0,
    ai_suggested: false,
    deleted_at: null,
    size: 'L',
    story_points: 5,
    created_at: '2026-04-07T08:00:00Z',
    updated_at: '2026-04-09T14:00:00Z',
  },
  {
    id: 't6',
    title: 'Sprint Board — drag & drop kolumny',
    description: '@hello-pangea/dnd, optimistic updates, WIP limit',
    status: 'in_progress',
    priority: 'high',
    type: 'development',
    project_id: 'p1',
    assignee_id: 'u2',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: '2026-04-12',
    position: 1,
    ai_suggested: false,
    deleted_at: null,
    size: 'XL',
    story_points: 8,
    created_at: '2026-04-08T09:00:00Z',
    updated_at: '2026-04-09T16:00:00Z',
  },
  // DONE
  {
    id: 't7',
    title: 'Setup projektu Next.js 15 + Supabase',
    description: null,
    status: 'done',
    priority: 'high',
    type: 'ops',
    project_id: 'p1',
    assignee_id: 'u1',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: null,
    position: 0,
    ai_suggested: false,
    deleted_at: null,
    size: 'M',
    story_points: 3,
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-04-03T17:00:00Z',
  },
  {
    id: 't8',
    title: 'Schemat bazy danych — migracje SQL',
    description: null,
    status: 'done',
    priority: 'high',
    type: 'ops',
    project_id: 'p1',
    assignee_id: 'u2',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: null,
    position: 1,
    ai_suggested: false,
    deleted_at: null,
    size: 'L',
    story_points: 5,
    created_at: '2026-04-02T08:00:00Z',
    updated_at: '2026-04-04T15:00:00Z',
  },
  {
    id: 't9',
    title: 'Brief oferty partnerskiej — hotel A',
    description: null,
    status: 'done',
    priority: 'medium',
    type: 'marketing',
    project_id: 'p3',
    assignee_id: 'u3',
    parent_task_id: null,
    cycle_id: 'c4',
    due_date: null,
    position: 2,
    ai_suggested: false,
    deleted_at: null,
    size: 'S',
    story_points: 2,
    created_at: '2026-04-05T10:00:00Z',
    updated_at: '2026-04-06T11:00:00Z',
  },
]

export const MOCK_IDEAS: DbIdea[] = [
  {
    id: 'i1',
    title: 'Integracja z Google Calendar dla hoteli',
    description: 'Auto-blokowanie dat w kalendarzu Google gdy rezerwacja potwierdzona',
    status: 'inbox',
    ice_impact: 8,
    ice_confidence: 6,
    ice_ease: 4,
    ice_score: 6.0,
    rejection_reason: null,
    source: 'founders_meeting',
    promoted_to_task_id: null,
    author_id: 'u1',
    created_at: '2026-04-09T10:00:00Z',
    updated_at: '2026-04-09T10:00:00Z',
  },
  {
    id: 'i2',
    title: 'Weekly digest email dla właścicieli hoteli',
    description: 'Automatyczny email w poniedziałek ze statystykami tygodniowymi',
    status: 'accepted',
    ice_impact: 7,
    ice_confidence: 8,
    ice_ease: 7,
    ice_score: 7.3,
    rejection_reason: null,
    source: 'user_feedback',
    promoted_to_task_id: null,
    author_id: 'u2',
    created_at: '2026-04-07T14:00:00Z',
    updated_at: '2026-04-08T09:00:00Z',
  },
  {
    id: 'i3',
    title: 'Chat w czasie rzeczywistym hotel–gość',
    description: 'Wbudowany czat do komunikacji po rezerwacji',
    status: 'rejected',
    ice_impact: 6,
    ice_confidence: 4,
    ice_ease: 2,
    ice_score: 4.0,
    rejection_reason: 'Poza scope 1.0, wysoki koszt utrzymania. Rozważyć w 2.0',
    source: 'market',
    promoted_to_task_id: null,
    author_id: 'u3',
    created_at: '2026-04-06T11:00:00Z',
    updated_at: '2026-04-07T10:00:00Z',
  },
  {
    id: 'i4',
    title: 'Dark mode dla panelu hotelu',
    description: null,
    status: 'inbox',
    ice_impact: 4,
    ice_confidence: 9,
    ice_ease: 8,
    ice_score: 7.0,
    rejection_reason: null,
    source: 'other',
    promoted_to_task_id: null,
    author_id: 'u1',
    created_at: '2026-04-10T16:00:00Z',
    updated_at: '2026-04-10T16:00:00Z',
  },
]

export const MOCK_DOCUMENTS: DbDocument[] = [
  {
    id: 'd1',
    title: 'ADR-001: Wybór Supabase jako backend',
    type: 'adr',
    status: 'accepted',
    content: '## Kontekst\n\nPotrzebujemy bazy danych z Auth i Realtime...\n\n## Decyzja\n\nWybieramy Supabase...',
    project_id: 'p1',
    author_id: 'u1',
    created_at: '2026-04-02T10:00:00Z',
    updated_at: '2026-04-02T10:00:00Z',
  },
  {
    id: 'd2',
    title: 'RFC-002: Architektura systemu rezerwacji',
    type: 'rfc',
    status: 'review',
    content: '## Problem\n\nJak obsługiwać konflikty rezerwacji w czasie rzeczywistym...',
    project_id: 'p1',
    author_id: 'u2',
    created_at: '2026-04-05T14:00:00Z',
    updated_at: '2026-04-06T09:00:00Z',
  },
]

export const MOCK_GOALS: DbGoal[] = [
  // Objectives
  {
    id: 'g1',
    title: 'Uruchomić platformę rezerwacji MVP',
    type: 'objective',
    status: 'on_track',
    description: 'Platforma dostępna dla pierwszych hotelowych partnerów pilotażowych',
    progress: 55,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-06-30',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q2 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'g2',
    title: 'Zbudować trakcję sprzedażową',
    type: 'objective',
    status: 'at_risk',
    description: 'Pozyskać pierwszych płacących klientów i walidacja modelu',
    progress: 20,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-09-30',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q3 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  // Key Results dla g1
  {
    id: 'g3',
    title: 'Auth + onboarding hotelu działają end-to-end',
    type: 'key_result',
    status: 'on_track',
    description: null,
    progress: 80,
    project_id: null,
    parent_goal_id: 'g1',
    due_date: '2026-04-30',
    target_value: 100,
    current_value: 80,
    unit: '%',
    quarter: 'Q2 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'g4',
    title: 'System rezerwacji obsługuje 100 transakcji testowych',
    type: 'key_result',
    status: 'at_risk',
    description: null,
    progress: 30,
    project_id: null,
    parent_goal_id: 'g1',
    due_date: '2026-05-31',
    target_value: 100,
    current_value: 30,
    unit: 'transakcji',
    quarter: 'Q2 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'g5',
    title: '3 hotele pilotażowe aktywne na platformie',
    type: 'key_result',
    status: 'on_track',
    description: null,
    progress: 33,
    project_id: null,
    parent_goal_id: 'g1',
    due_date: '2026-06-30',
    target_value: 3,
    current_value: 1,
    unit: 'hoteli',
    quarter: 'Q2 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  // Key Results dla g2
  {
    id: 'g6',
    title: '10 demo call z potencjalnymi hotelami',
    type: 'key_result',
    status: 'on_track',
    description: null,
    progress: 40,
    project_id: null,
    parent_goal_id: 'g2',
    due_date: '2026-06-30',
    target_value: 10,
    current_value: 4,
    unit: 'demo calls',
    quarter: 'Q2 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'g7',
    title: 'MRR ≥ 2 000 PLN',
    type: 'key_result',
    status: 'off_track',
    description: null,
    progress: 0,
    project_id: null,
    parent_goal_id: 'g2',
    due_date: '2026-09-30',
    target_value: 2000,
    current_value: 0,
    unit: 'PLN',
    quarter: 'Q3 2026',
    budget_planned_pln: null,
    budget_actual_pln: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  // Grant Milestones PARP
  {
    id: 'g8',
    title: 'M1 — Uruchomienie projektu i kick-off',
    type: 'grant_milestone',
    status: 'achieved',
    description: 'Rejestracja projektu, umowa z PARP, pierwsze raportowanie',
    progress: 100,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-01-31',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q1 2026',
    budget_planned_pln: 50000,
    budget_actual_pln: 48500,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-31T00:00:00Z',
  },
  {
    id: 'g9',
    title: 'M2 — Prototyp platformy i walidacja techniczna',
    type: 'grant_milestone',
    status: 'at_risk',
    description: 'Demo działającej platformy, dokumentacja techniczna, testy bezpieczeństwa',
    progress: 65,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-04-30',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q2 2026',
    budget_planned_pln: 120000,
    budget_actual_pln: 87000,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'g10',
    title: 'M3 — Pilotaż z pierwszymi partnerami',
    type: 'grant_milestone',
    status: 'on_track',
    description: 'Min. 3 hotele aktywne, raport z pilotażu, metryki użycia',
    progress: 0,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-07-31',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q3 2026',
    budget_planned_pln: 150000,
    budget_actual_pln: 0,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'g11',
    title: 'M4 — Komercjalizacja i raport końcowy',
    type: 'grant_milestone',
    status: 'on_track',
    description: 'Pełne wdrożenie, raport końcowy do PARP, rozliczenie grantu',
    progress: 0,
    project_id: null,
    parent_goal_id: null,
    due_date: '2026-12-15',
    target_value: null,
    current_value: null,
    unit: null,
    quarter: 'Q4 2026',
    budget_planned_pln: 180000,
    budget_actual_pln: 0,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]

// Helper: pobierz taski per status (includes in_review column)
export function getTasksByStatus(tasks: DbTask[]) {
  return {
    todo:        tasks.filter((t) => t.status === 'todo'),
    in_progress: tasks.filter((t) => t.status === 'in_progress'),
    in_review:   tasks.filter((t) => t.status === 'in_review'),
    done:        tasks.filter((t) => t.status === 'done'),
    cancelled:   tasks.filter((t) => t.status === 'cancelled'),
  }
}

// Helper: wzbogać task o relacje
export function enrichTask(task: DbTask): TaskWithRelations {
  return {
    ...task,
    project: MOCK_PROJECTS.find((p) => p.id === task.project_id)!,
    assignee: MOCK_USERS.find((u) => u.id === task.assignee_id) ?? null,
    subtasks: MOCK_TASKS.filter((t) => t.parent_task_id === task.id),
  }
}
